### ISSUE TITLE
Getting Type Error: Failed to fetch

### ISSUE THREAD

**Issue by Krobo224** [iyaja/llama-fs#47]
<img width="1101" alt="image" src="https://github.com/iyaja/llama-fs/assets/72267398/96a77f71-323a-404a-ac1e-75ab1e626805">

**Comment by jlwainwright** [comment]
Same issue here. 

MacOS

**Comment by Alpha-Half** [comment]
make sure:
1.  server is on localhost:8000
2. no internet problem to Groq servers
